# loading repositories, dependencies files to locate artifacts
Dir[File.dirname(__FILE__) + '/build/*.rb'].each {|file| require file }

VERSION_NUMBER = "1.0.0"
GROUP = "spring-petclinic"
COPYRIGHT = "Springsource 2008"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"
repositories.remote << "http://www.ibiblio.org/maven2/"

# Spring repos
%w(release external milestone snapshot).each do |repo|
  repositories.remote << "http://repository.springsource.com/maven/bundles/#{repo}"
end

desc "The Spring Petclinic application"
define "spring-petclinic" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  compile.with transitive(SPRING, ASPECTJ, SLF4J, LOG4J, DBCP, POOL, HSQLDB, HIBERNATE, JPA, TOPLINK, SERVLET, TAGLIBS, SYNDICATION, JDOM, JAXB, TRANSACTION)
  resources

  test.compile.with SPRING_TEST
  test.resources
  package(:war)
end

