require 'buildr'
require 'buildr/jetty'
require 'readline'
require 'zip/zip'

CURRENT_DIR = File.dirname(__FILE__)

# loading repositories, dependencies files to locate artifacts
Dir[CURRENT_DIR + '/build/*.rb'].each {|file| require file }

VERSION_NUMBER = "1.0.0"
GROUP = "spring-petclinic"
COPYRIGHT = "Springsource 2008"

desc "The Spring Petclinic application"
define "spring-petclinic" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  compile.with transitive(SPRING, ASPECTJ, SLF4J, LOG4J, DBCP, POOL, HSQLDB, HIBERNATE, JPA, TOPLINK, SERVLET, TAGLIBS, SYNDICATION, JDOM, JAXB, TRANSACTION)
  resources

  test.compile.with SPRING_TEST
  test.resources

  package(:war)

  task("jetty"=>[package(:war), jetty.use]) do |task|
    jetty.deploy("http://localhost:8080", task.prerequisites.first)
    Readline::readline('[Type ENTER to stop Jetty]')
  end

end

