VERSION_NUMBER = "1.0.0"
GROUP = "spring-petclinic"
COPYRIGHT = "Springsource 2008"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"
repositories.remote << "http://www.ibiblio.org/maven2/"

# Spring repos
%w(release external milestone snapshot).each do |repo|
  repositories.remote << "http://repository.springsource.com/maven/bundles/#{repo}"
end

# Dependencies
SPRING = group('org.springframework.context', 'org.springframework.orm', 'org.springframework.oxm', 'org.springframework.web.servlet', 'org.springframework.aspects', :under => 'org.springframework', :version => '3.0.0.RELEASE')

ASPECTJ = 'org.aspectj:com.springsource.org.aspectj.weaver:jar:1.6.8.RELEASE'

SLF4J = group('com.springsource.slf4j.api', 'com.springsource.slf4j.org.apache.commons.logging', 'com.springsource.slf4j.log4j', 
:under => 'org.slf4j', :version => '1.5.6')

LOG4J = 'org.apache.log4j:com.springsource.org.apache.log4j:jar:1.2.15'
DBCP = 'org.apache.commons:com.springsource.org.apache.commons.dbcp:jar:1.2.2.osgi'
POOL = 'org.apache.commons:com.springsource.org.apache.commons.pool:jar:1.5.3'
HSQLDB = 'org.hsqldb:com.springsource.org.hsqldb:jar:1.8.0.9'

HIBERNATE = ['org.hibernate:com.springsource.org.hibernate:jar:3.3.2.GA', 'org.hibernate:com.springsource.org.hibernate.ejb:jar:3.4.0.GA', 
'org.hibernate:com.springsource.org.hibernate.annotations:jar:3.4.0.GA']

JPA = ['javax.persistence:com.springsource.javax.persistence:jar:1.0.0', 'org.apache.openjpa:com.springsource.org.apache.openjpa:jar:1.1.0']

TOPLINK = 'com.oracle.toplink.essentials:com.springsource.oracle.toplink.essentials:jar:2.0.0.b41-beta2'


SERVLET = ['javax.servlet:com.springsource.javax.servlet:jar:2.5.0', 'javax.servlet:com.springsource.javax.servlet.jsp:jar:2.1.0', 'javax.servlet:com.springsource.javax.servlet.jsp.jstl:jar:1.2.0']

TAGLIBS = 'org.apache.taglibs:com.springsource.org.apache.taglibs.standard:jar:1.1.2'

SYNDICATION = 'com.sun.syndication:com.springsource.com.sun.syndication:jar:1.0.0'

JDOM = 'org.jdom:com.springsource.org.jdom:jar:1.1.0'
JAXB = 'javax.xml.bind:com.springsource.javax.xml.bind:jar:2.1.7'

SPRING_TEST = 'org.springframework:org.springframework.test:jar:3.0.0.RELEASE'

TRANSACTION = 'javax.transaction:com.springsource.javax.transaction:jar:1.1.0'

desc "The Spring Petclinic application"
define "spring-petclinic" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  compile.with transitive(SPRING, ASPECTJ, SLF4J, LOG4J, DBCP, POOL, HSQLDB, HIBERNATE, JPA, TOPLINK, SERVLET, TAGLIBS, SYNDICATION, JDOM, JAXB, TRANSACTION)
  resources

  test.compile.with SPRING_TEST
  test.resources
  package(:jar)
end

